name: 24/7 Bot Runner

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *' # يعمل تلقائياً كل 6 ساعات

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Telethon
        run: pip install telethon

      - name: Start Bot
        run: |
          chmod 666 bot_session.session
          python main.py
